package com.xuecheng.generator;

import com.baomidou.mybatisplus.annotation.DbType;
import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.generator.AutoGenerator;
import com.baomidou.mybatisplus.generator.config.*;
import com.baomidou.mybatisplus.generator.config.po.TableFill;
import com.baomidou.mybatisplus.generator.config.rules.NamingStrategy;
import com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine;

import java.util.Arrays;

/**
 * MyBatis-Plus Code Generation Class
 */
public class UcenterCodeGenerator {

	// TODO Modify the service name and data table name
	private static final String SERVICE_NAME = "ucenter";

	//Database Account
	private static final String DATA_SOURCE_USER_NAME  = "root";
	//Database password
	private static final String DATA_SOURCE_PASSWORD  = "mysql";
	//Generated table
	private static final String[] TABLE_NAMES = new String[]{
			"xc_company",
			"xc_company_user",
			"xc_menu",
			"xc_permission",
			"xc_role",
			"xc_teacher",
			"xc_user",
			"xc_user_role"
	};

	// TODO Entity is generated by default, and DTO needs to be generated to modify this variable
	// Generally, you need to generate the DTO class first, then modify this parameter and generate the PO class.
	private static final Boolean IS_DTO = false;

	public static void main(String[] args) {
		// Code generator
		AutoGenerator mpg = new AutoGenerator();
		// Select freemarker engine, default Velocity
		mpg.setTemplateEngine(new FreemarkerTemplateEngine());
		// Global Configuration
		GlobalConfig gc = new GlobalConfig();
		gc.setFileOverride(true);
		//Generate Path
		gc.setOutputDir(System.getProperty("user.dir") + "/xuecheng-plus-generator/src/main/java");
		gc.setAuthor("itcast");
		gc.setOpen(false);
		gc.setSwagger2(false);
		gc.setServiceName("%sService");
        gc.setBaseResultMap(true);
        gc.setBaseColumnList(true);

		if (IS_DTO) {
			gc.setSwagger2(true);
			gc.setEntityName("%sDTO");
		}
		mpg.setGlobalConfig(gc);

		// Database Configuration
		DataSourceConfig dsc = new DataSourceConfig();
		dsc.setDbType(DbType.MYSQL);
		dsc.setUrl("jdbc:mysql://192.168.101.65:3306/xcplus_users"
				+ "?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8");
//		dsc.setDriverName("com.mysql.jdbc.Driver");
		dsc.setDriverName("com.mysql.cj.jdbc.Driver");
		dsc.setUsername(DATA_SOURCE_USER_NAME);
		dsc.setPassword(DATA_SOURCE_PASSWORD);
		mpg.setDataSource(dsc);

		// Package Configuration
		PackageConfig pc = new PackageConfig();
		pc.setModuleName(SERVICE_NAME);
		pc.setParent("com.xuecheng");

		pc.setServiceImpl("service.impl");
		pc.setXml("mapper");
		pc.setEntity("model.po");
		mpg.setPackageInfo(pc);


		// Setting up the template
		TemplateConfig tc = new TemplateConfig();
		mpg.setTemplate(tc);

		// Policy Configuration
		StrategyConfig strategy = new StrategyConfig();
		strategy.setNaming(NamingStrategy.underline_to_camel);
		strategy.setColumnNaming(NamingStrategy.underline_to_camel);
		strategy.setEntityLombokModel(true);
		strategy.setRestControllerStyle(true);
		strategy.setInclude(TABLE_NAMES);
		strategy.setControllerMappingHyphenStyle(true);
		strategy.setTablePrefix(pc.getModuleName() + "_");
		// Whether to remove the is prefix from Boolean type fields
		strategy.setEntityBooleanColumnRemoveIsPrefix(true);
		strategy.setRestControllerStyle(true);

		// Autofill Field Configuration
		strategy.setTableFillList(Arrays.asList(
				new TableFill("create_date", FieldFill.INSERT),
				new TableFill("change_date", FieldFill.INSERT_UPDATE),
				new TableFill("modify_date", FieldFill.UPDATE)
		));
		mpg.setStrategy(strategy);

		mpg.execute();
	}

}
